// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostIt.proto

package nl.hu.blackboard.data;

public final class PostItProtos {
  private PostItProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PostItOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 timestep = 1;
    boolean hasTimestep();
    long getTimestep();
    
    // required string payload = 2;
    boolean hasPayload();
    String getPayload();
    
    // optional string owner = 3;
    boolean hasOwner();
    String getOwner();
    
    // optional bool isProcessed = 4;
    boolean hasIsProcessed();
    boolean getIsProcessed();
    
    // optional int32 ordinal = 5;
    boolean hasOrdinal();
    int getOrdinal();
    
    // optional string productRef = 6;
    boolean hasProductRef();
    String getProductRef();
  }
  public static final class PostIt extends
      com.google.protobuf.GeneratedMessage
      implements PostItOrBuilder {
    // Use PostIt.newBuilder() to construct.
    private PostIt(Builder builder) {
      super(builder);
    }
    private PostIt(boolean noInit) {}
    
    private static final PostIt defaultInstance;
    public static PostIt getDefaultInstance() {
      return defaultInstance;
    }
    
    public PostIt getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostIt_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostIt_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 timestep = 1;
    public static final int TIMESTEP_FIELD_NUMBER = 1;
    private long timestep_;
    public boolean hasTimestep() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestep() {
      return timestep_;
    }
    
    // required string payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private java.lang.Object payload_;
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          payload_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string owner = 3;
    public static final int OWNER_FIELD_NUMBER = 3;
    private java.lang.Object owner_;
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          owner_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool isProcessed = 4;
    public static final int ISPROCESSED_FIELD_NUMBER = 4;
    private boolean isProcessed_;
    public boolean hasIsProcessed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getIsProcessed() {
      return isProcessed_;
    }
    
    // optional int32 ordinal = 5;
    public static final int ORDINAL_FIELD_NUMBER = 5;
    private int ordinal_;
    public boolean hasOrdinal() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getOrdinal() {
      return ordinal_;
    }
    
    // optional string productRef = 6;
    public static final int PRODUCTREF_FIELD_NUMBER = 6;
    private java.lang.Object productRef_;
    public boolean hasProductRef() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getProductRef() {
      java.lang.Object ref = productRef_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          productRef_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProductRefBytes() {
      java.lang.Object ref = productRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        productRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      timestep_ = 0L;
      payload_ = "";
      owner_ = "";
      isProcessed_ = false;
      ordinal_ = 0;
      productRef_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestep_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPayloadBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOwnerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isProcessed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, ordinal_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getProductRefBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestep_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPayloadBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOwnerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isProcessed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ordinal_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getProductRefBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostIt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nl.hu.blackboard.data.PostItProtos.PostIt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nl.hu.blackboard.data.PostItProtos.PostItOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostIt_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostIt_fieldAccessorTable;
      }
      
      // Construct using nl.hu.blackboard.data.PostItProtos.PostIt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestep_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        owner_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        isProcessed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        ordinal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        productRef_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.hu.blackboard.data.PostItProtos.PostIt.getDescriptor();
      }
      
      public nl.hu.blackboard.data.PostItProtos.PostIt getDefaultInstanceForType() {
        return nl.hu.blackboard.data.PostItProtos.PostIt.getDefaultInstance();
      }
      
      public nl.hu.blackboard.data.PostItProtos.PostIt build() {
        nl.hu.blackboard.data.PostItProtos.PostIt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nl.hu.blackboard.data.PostItProtos.PostIt buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nl.hu.blackboard.data.PostItProtos.PostIt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nl.hu.blackboard.data.PostItProtos.PostIt buildPartial() {
        nl.hu.blackboard.data.PostItProtos.PostIt result = new nl.hu.blackboard.data.PostItProtos.PostIt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestep_ = timestep_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.owner_ = owner_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isProcessed_ = isProcessed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ordinal_ = ordinal_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.productRef_ = productRef_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.hu.blackboard.data.PostItProtos.PostIt) {
          return mergeFrom((nl.hu.blackboard.data.PostItProtos.PostIt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nl.hu.blackboard.data.PostItProtos.PostIt other) {
        if (other == nl.hu.blackboard.data.PostItProtos.PostIt.getDefaultInstance()) return this;
        if (other.hasTimestep()) {
          setTimestep(other.getTimestep());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasOwner()) {
          setOwner(other.getOwner());
        }
        if (other.hasIsProcessed()) {
          setIsProcessed(other.getIsProcessed());
        }
        if (other.hasOrdinal()) {
          setOrdinal(other.getOrdinal());
        }
        if (other.hasProductRef()) {
          setProductRef(other.getProductRef());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPayload()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestep_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              payload_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              owner_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isProcessed_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ordinal_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              productRef_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 timestep = 1;
      private long timestep_ ;
      public boolean hasTimestep() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestep() {
        return timestep_;
      }
      public Builder setTimestep(long value) {
        bitField0_ |= 0x00000001;
        timestep_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestep() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestep_ = 0L;
        onChanged();
        return this;
      }
      
      // required string payload = 2;
      private java.lang.Object payload_ = "";
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          payload_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPayload(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
        return this;
      }
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      void setPayload(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
      }
      
      // optional string owner = 3;
      private java.lang.Object owner_ = "";
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOwner(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        owner_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwner() {
        bitField0_ = (bitField0_ & ~0x00000004);
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      void setOwner(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        owner_ = value;
        onChanged();
      }
      
      // optional bool isProcessed = 4;
      private boolean isProcessed_ ;
      public boolean hasIsProcessed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getIsProcessed() {
        return isProcessed_;
      }
      public Builder setIsProcessed(boolean value) {
        bitField0_ |= 0x00000008;
        isProcessed_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsProcessed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isProcessed_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 ordinal = 5;
      private int ordinal_ ;
      public boolean hasOrdinal() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getOrdinal() {
        return ordinal_;
      }
      public Builder setOrdinal(int value) {
        bitField0_ |= 0x00000010;
        ordinal_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrdinal() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ordinal_ = 0;
        onChanged();
        return this;
      }
      
      // optional string productRef = 6;
      private java.lang.Object productRef_ = "";
      public boolean hasProductRef() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getProductRef() {
        java.lang.Object ref = productRef_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          productRef_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProductRef(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        productRef_ = value;
        onChanged();
        return this;
      }
      public Builder clearProductRef() {
        bitField0_ = (bitField0_ & ~0x00000020);
        productRef_ = getDefaultInstance().getProductRef();
        onChanged();
        return this;
      }
      void setProductRef(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        productRef_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:nl.hu.blackboard.data.PostIt)
    }
    
    static {
      defaultInstance = new PostIt(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nl.hu.blackboard.data.PostIt)
  }
  
  public interface PostItBoxOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool isWrite = 1;
    boolean hasIsWrite();
    boolean getIsWrite();
    
    // required string zone = 2;
    boolean hasZone();
    String getZone();
    
    // repeated .nl.hu.blackboard.data.PostIt postIts = 3;
    java.util.List<nl.hu.blackboard.data.PostItProtos.PostIt> 
        getPostItsList();
    nl.hu.blackboard.data.PostItProtos.PostIt getPostIts(int index);
    int getPostItsCount();
    java.util.List<? extends nl.hu.blackboard.data.PostItProtos.PostItOrBuilder> 
        getPostItsOrBuilderList();
    nl.hu.blackboard.data.PostItProtos.PostItOrBuilder getPostItsOrBuilder(
        int index);
    
    // optional string readOwner = 4;
    boolean hasReadOwner();
    String getReadOwner();
    
    // optional int64 currentTimeStep = 5;
    boolean hasCurrentTimeStep();
    long getCurrentTimeStep();
    
    // optional .nl.hu.blackboard.data.PostItBox.Filter filter = 6;
    boolean hasFilter();
    nl.hu.blackboard.data.PostItProtos.PostItBox.Filter getFilter();
    nl.hu.blackboard.data.PostItProtos.PostItBox.FilterOrBuilder getFilterOrBuilder();
  }
  public static final class PostItBox extends
      com.google.protobuf.GeneratedMessage
      implements PostItBoxOrBuilder {
    // Use PostItBox.newBuilder() to construct.
    private PostItBox(Builder builder) {
      super(builder);
    }
    private PostItBox(boolean noInit) {}
    
    private static final PostItBox defaultInstance;
    public static PostItBox getDefaultInstance() {
      return defaultInstance;
    }
    
    public PostItBox getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_fieldAccessorTable;
    }
    
    public interface FilterOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string filtername = 1;
      boolean hasFiltername();
      String getFiltername();
      
      // repeated string agentname = 2;
      java.util.List<String> getAgentnameList();
      int getAgentnameCount();
      String getAgentname(int index);
      
      // optional int64 deadline = 3;
      boolean hasDeadline();
      long getDeadline();
    }
    public static final class Filter extends
        com.google.protobuf.GeneratedMessage
        implements FilterOrBuilder {
      // Use Filter.newBuilder() to construct.
      private Filter(Builder builder) {
        super(builder);
      }
      private Filter(boolean noInit) {}
      
      private static final Filter defaultInstance;
      public static Filter getDefaultInstance() {
        return defaultInstance;
      }
      
      public Filter getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string filtername = 1;
      public static final int FILTERNAME_FIELD_NUMBER = 1;
      private java.lang.Object filtername_;
      public boolean hasFiltername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFiltername() {
        java.lang.Object ref = filtername_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            filtername_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getFilternameBytes() {
        java.lang.Object ref = filtername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          filtername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // repeated string agentname = 2;
      public static final int AGENTNAME_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList agentname_;
      public java.util.List<String>
          getAgentnameList() {
        return agentname_;
      }
      public int getAgentnameCount() {
        return agentname_.size();
      }
      public String getAgentname(int index) {
        return agentname_.get(index);
      }
      
      // optional int64 deadline = 3;
      public static final int DEADLINE_FIELD_NUMBER = 3;
      private long deadline_;
      public boolean hasDeadline() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getDeadline() {
        return deadline_;
      }
      
      private void initFields() {
        filtername_ = "";
        agentname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        deadline_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasFiltername()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getFilternameBytes());
        }
        for (int i = 0; i < agentname_.size(); i++) {
          output.writeBytes(2, agentname_.getByteString(i));
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(3, deadline_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getFilternameBytes());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < agentname_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(agentname_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getAgentnameList().size();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, deadline_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static nl.hu.blackboard.data.PostItProtos.PostItBox.Filter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(nl.hu.blackboard.data.PostItProtos.PostItBox.Filter prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements nl.hu.blackboard.data.PostItProtos.PostItBox.FilterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_fieldAccessorTable;
        }
        
        // Construct using nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          filtername_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          agentname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          deadline_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDescriptor();
        }
        
        public nl.hu.blackboard.data.PostItProtos.PostItBox.Filter getDefaultInstanceForType() {
          return nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDefaultInstance();
        }
        
        public nl.hu.blackboard.data.PostItProtos.PostItBox.Filter build() {
          nl.hu.blackboard.data.PostItProtos.PostItBox.Filter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private nl.hu.blackboard.data.PostItProtos.PostItBox.Filter buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          nl.hu.blackboard.data.PostItProtos.PostItBox.Filter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public nl.hu.blackboard.data.PostItProtos.PostItBox.Filter buildPartial() {
          nl.hu.blackboard.data.PostItProtos.PostItBox.Filter result = new nl.hu.blackboard.data.PostItProtos.PostItBox.Filter(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.filtername_ = filtername_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            agentname_ = new com.google.protobuf.UnmodifiableLazyStringList(
                agentname_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.agentname_ = agentname_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000002;
          }
          result.deadline_ = deadline_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof nl.hu.blackboard.data.PostItProtos.PostItBox.Filter) {
            return mergeFrom((nl.hu.blackboard.data.PostItProtos.PostItBox.Filter)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(nl.hu.blackboard.data.PostItProtos.PostItBox.Filter other) {
          if (other == nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDefaultInstance()) return this;
          if (other.hasFiltername()) {
            setFiltername(other.getFiltername());
          }
          if (!other.agentname_.isEmpty()) {
            if (agentname_.isEmpty()) {
              agentname_ = other.agentname_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAgentnameIsMutable();
              agentname_.addAll(other.agentname_);
            }
            onChanged();
          }
          if (other.hasDeadline()) {
            setDeadline(other.getDeadline());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasFiltername()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                filtername_ = input.readBytes();
                break;
              }
              case 18: {
                ensureAgentnameIsMutable();
                agentname_.add(input.readBytes());
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                deadline_ = input.readInt64();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string filtername = 1;
        private java.lang.Object filtername_ = "";
        public boolean hasFiltername() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getFiltername() {
          java.lang.Object ref = filtername_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            filtername_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setFiltername(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          filtername_ = value;
          onChanged();
          return this;
        }
        public Builder clearFiltername() {
          bitField0_ = (bitField0_ & ~0x00000001);
          filtername_ = getDefaultInstance().getFiltername();
          onChanged();
          return this;
        }
        void setFiltername(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          filtername_ = value;
          onChanged();
        }
        
        // repeated string agentname = 2;
        private com.google.protobuf.LazyStringList agentname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureAgentnameIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            agentname_ = new com.google.protobuf.LazyStringArrayList(agentname_);
            bitField0_ |= 0x00000002;
           }
        }
        public java.util.List<String>
            getAgentnameList() {
          return java.util.Collections.unmodifiableList(agentname_);
        }
        public int getAgentnameCount() {
          return agentname_.size();
        }
        public String getAgentname(int index) {
          return agentname_.get(index);
        }
        public Builder setAgentname(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureAgentnameIsMutable();
          agentname_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addAgentname(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureAgentnameIsMutable();
          agentname_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllAgentname(
            java.lang.Iterable<String> values) {
          ensureAgentnameIsMutable();
          super.addAll(values, agentname_);
          onChanged();
          return this;
        }
        public Builder clearAgentname() {
          agentname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        void addAgentname(com.google.protobuf.ByteString value) {
          ensureAgentnameIsMutable();
          agentname_.add(value);
          onChanged();
        }
        
        // optional int64 deadline = 3;
        private long deadline_ ;
        public boolean hasDeadline() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public long getDeadline() {
          return deadline_;
        }
        public Builder setDeadline(long value) {
          bitField0_ |= 0x00000004;
          deadline_ = value;
          onChanged();
          return this;
        }
        public Builder clearDeadline() {
          bitField0_ = (bitField0_ & ~0x00000004);
          deadline_ = 0L;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:nl.hu.blackboard.data.PostItBox.Filter)
      }
      
      static {
        defaultInstance = new Filter(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:nl.hu.blackboard.data.PostItBox.Filter)
    }
    
    private int bitField0_;
    // required bool isWrite = 1;
    public static final int ISWRITE_FIELD_NUMBER = 1;
    private boolean isWrite_;
    public boolean hasIsWrite() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getIsWrite() {
      return isWrite_;
    }
    
    // required string zone = 2;
    public static final int ZONE_FIELD_NUMBER = 2;
    private java.lang.Object zone_;
    public boolean hasZone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getZone() {
      java.lang.Object ref = zone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          zone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getZoneBytes() {
      java.lang.Object ref = zone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        zone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .nl.hu.blackboard.data.PostIt postIts = 3;
    public static final int POSTITS_FIELD_NUMBER = 3;
    private java.util.List<nl.hu.blackboard.data.PostItProtos.PostIt> postIts_;
    public java.util.List<nl.hu.blackboard.data.PostItProtos.PostIt> getPostItsList() {
      return postIts_;
    }
    public java.util.List<? extends nl.hu.blackboard.data.PostItProtos.PostItOrBuilder> 
        getPostItsOrBuilderList() {
      return postIts_;
    }
    public int getPostItsCount() {
      return postIts_.size();
    }
    public nl.hu.blackboard.data.PostItProtos.PostIt getPostIts(int index) {
      return postIts_.get(index);
    }
    public nl.hu.blackboard.data.PostItProtos.PostItOrBuilder getPostItsOrBuilder(
        int index) {
      return postIts_.get(index);
    }
    
    // optional string readOwner = 4;
    public static final int READOWNER_FIELD_NUMBER = 4;
    private java.lang.Object readOwner_;
    public boolean hasReadOwner() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getReadOwner() {
      java.lang.Object ref = readOwner_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          readOwner_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReadOwnerBytes() {
      java.lang.Object ref = readOwner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        readOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 currentTimeStep = 5;
    public static final int CURRENTTIMESTEP_FIELD_NUMBER = 5;
    private long currentTimeStep_;
    public boolean hasCurrentTimeStep() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getCurrentTimeStep() {
      return currentTimeStep_;
    }
    
    // optional .nl.hu.blackboard.data.PostItBox.Filter filter = 6;
    public static final int FILTER_FIELD_NUMBER = 6;
    private nl.hu.blackboard.data.PostItProtos.PostItBox.Filter filter_;
    public boolean hasFilter() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public nl.hu.blackboard.data.PostItProtos.PostItBox.Filter getFilter() {
      return filter_;
    }
    public nl.hu.blackboard.data.PostItProtos.PostItBox.FilterOrBuilder getFilterOrBuilder() {
      return filter_;
    }
    
    private void initFields() {
      isWrite_ = false;
      zone_ = "";
      postIts_ = java.util.Collections.emptyList();
      readOwner_ = "";
      currentTimeStep_ = 0L;
      filter_ = nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasIsWrite()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPostItsCount(); i++) {
        if (!getPostIts(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasFilter()) {
        if (!getFilter().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isWrite_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getZoneBytes());
      }
      for (int i = 0; i < postIts_.size(); i++) {
        output.writeMessage(3, postIts_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getReadOwnerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, currentTimeStep_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(6, filter_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isWrite_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getZoneBytes());
      }
      for (int i = 0; i < postIts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, postIts_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getReadOwnerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, currentTimeStep_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, filter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nl.hu.blackboard.data.PostItProtos.PostItBox parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nl.hu.blackboard.data.PostItProtos.PostItBox prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nl.hu.blackboard.data.PostItProtos.PostItBoxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.hu.blackboard.data.PostItProtos.internal_static_nl_hu_lcv_blackboard_data_PostItBox_fieldAccessorTable;
      }
      
      // Construct using nl.hu.blackboard.data.PostItProtos.PostItBox.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPostItsFieldBuilder();
          getFilterFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        isWrite_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        zone_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (postItsBuilder_ == null) {
          postIts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          postItsBuilder_.clear();
        }
        readOwner_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        currentTimeStep_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (filterBuilder_ == null) {
          filter_ = nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDefaultInstance();
        } else {
          filterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.hu.blackboard.data.PostItProtos.PostItBox.getDescriptor();
      }
      
      public nl.hu.blackboard.data.PostItProtos.PostItBox getDefaultInstanceForType() {
        return nl.hu.blackboard.data.PostItProtos.PostItBox.getDefaultInstance();
      }
      
      public nl.hu.blackboard.data.PostItProtos.PostItBox build() {
        nl.hu.blackboard.data.PostItProtos.PostItBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nl.hu.blackboard.data.PostItProtos.PostItBox buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nl.hu.blackboard.data.PostItProtos.PostItBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nl.hu.blackboard.data.PostItProtos.PostItBox buildPartial() {
        nl.hu.blackboard.data.PostItProtos.PostItBox result = new nl.hu.blackboard.data.PostItProtos.PostItBox(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isWrite_ = isWrite_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.zone_ = zone_;
        if (postItsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            postIts_ = java.util.Collections.unmodifiableList(postIts_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.postIts_ = postIts_;
        } else {
          result.postIts_ = postItsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.readOwner_ = readOwner_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.currentTimeStep_ = currentTimeStep_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        if (filterBuilder_ == null) {
          result.filter_ = filter_;
        } else {
          result.filter_ = filterBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.hu.blackboard.data.PostItProtos.PostItBox) {
          return mergeFrom((nl.hu.blackboard.data.PostItProtos.PostItBox)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nl.hu.blackboard.data.PostItProtos.PostItBox other) {
        if (other == nl.hu.blackboard.data.PostItProtos.PostItBox.getDefaultInstance()) return this;
        if (other.hasIsWrite()) {
          setIsWrite(other.getIsWrite());
        }
        if (other.hasZone()) {
          setZone(other.getZone());
        }
        if (postItsBuilder_ == null) {
          if (!other.postIts_.isEmpty()) {
            if (postIts_.isEmpty()) {
              postIts_ = other.postIts_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePostItsIsMutable();
              postIts_.addAll(other.postIts_);
            }
            onChanged();
          }
        } else {
          if (!other.postIts_.isEmpty()) {
            if (postItsBuilder_.isEmpty()) {
              postItsBuilder_.dispose();
              postItsBuilder_ = null;
              postIts_ = other.postIts_;
              bitField0_ = (bitField0_ & ~0x00000004);
              postItsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPostItsFieldBuilder() : null;
            } else {
              postItsBuilder_.addAllMessages(other.postIts_);
            }
          }
        }
        if (other.hasReadOwner()) {
          setReadOwner(other.getReadOwner());
        }
        if (other.hasCurrentTimeStep()) {
          setCurrentTimeStep(other.getCurrentTimeStep());
        }
        if (other.hasFilter()) {
          mergeFilter(other.getFilter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasIsWrite()) {
          
          return false;
        }
        if (!hasZone()) {
          
          return false;
        }
        for (int i = 0; i < getPostItsCount(); i++) {
          if (!getPostIts(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasFilter()) {
          if (!getFilter().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isWrite_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              zone_ = input.readBytes();
              break;
            }
            case 26: {
              nl.hu.blackboard.data.PostItProtos.PostIt.Builder subBuilder = nl.hu.blackboard.data.PostItProtos.PostIt.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPostIts(subBuilder.buildPartial());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              readOwner_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              currentTimeStep_ = input.readInt64();
              break;
            }
            case 50: {
              nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.Builder subBuilder = nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.newBuilder();
              if (hasFilter()) {
                subBuilder.mergeFrom(getFilter());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFilter(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool isWrite = 1;
      private boolean isWrite_ ;
      public boolean hasIsWrite() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getIsWrite() {
        return isWrite_;
      }
      public Builder setIsWrite(boolean value) {
        bitField0_ |= 0x00000001;
        isWrite_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsWrite() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isWrite_ = false;
        onChanged();
        return this;
      }
      
      // required string zone = 2;
      private java.lang.Object zone_ = "";
      public boolean hasZone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getZone() {
        java.lang.Object ref = zone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          zone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setZone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        zone_ = value;
        onChanged();
        return this;
      }
      public Builder clearZone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        zone_ = getDefaultInstance().getZone();
        onChanged();
        return this;
      }
      void setZone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        zone_ = value;
        onChanged();
      }
      
      // repeated .nl.hu.blackboard.data.PostIt postIts = 3;
      private java.util.List<nl.hu.blackboard.data.PostItProtos.PostIt> postIts_ =
        java.util.Collections.emptyList();
      private void ensurePostItsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          postIts_ = new java.util.ArrayList<nl.hu.blackboard.data.PostItProtos.PostIt>(postIts_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          nl.hu.blackboard.data.PostItProtos.PostIt, nl.hu.blackboard.data.PostItProtos.PostIt.Builder, nl.hu.blackboard.data.PostItProtos.PostItOrBuilder> postItsBuilder_;
      
      public java.util.List<nl.hu.blackboard.data.PostItProtos.PostIt> getPostItsList() {
        if (postItsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(postIts_);
        } else {
          return postItsBuilder_.getMessageList();
        }
      }
      public int getPostItsCount() {
        if (postItsBuilder_ == null) {
          return postIts_.size();
        } else {
          return postItsBuilder_.getCount();
        }
      }
      public nl.hu.blackboard.data.PostItProtos.PostIt getPostIts(int index) {
        if (postItsBuilder_ == null) {
          return postIts_.get(index);
        } else {
          return postItsBuilder_.getMessage(index);
        }
      }
      public Builder setPostIts(
          int index, nl.hu.blackboard.data.PostItProtos.PostIt value) {
        if (postItsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostItsIsMutable();
          postIts_.set(index, value);
          onChanged();
        } else {
          postItsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPostIts(
          int index, nl.hu.blackboard.data.PostItProtos.PostIt.Builder builderForValue) {
        if (postItsBuilder_ == null) {
          ensurePostItsIsMutable();
          postIts_.set(index, builderForValue.build());
          onChanged();
        } else {
          postItsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPostIts(nl.hu.blackboard.data.PostItProtos.PostIt value) {
        if (postItsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostItsIsMutable();
          postIts_.add(value);
          onChanged();
        } else {
          postItsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPostIts(
          int index, nl.hu.blackboard.data.PostItProtos.PostIt value) {
        if (postItsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostItsIsMutable();
          postIts_.add(index, value);
          onChanged();
        } else {
          postItsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPostIts(
          nl.hu.blackboard.data.PostItProtos.PostIt.Builder builderForValue) {
        if (postItsBuilder_ == null) {
          ensurePostItsIsMutable();
          postIts_.add(builderForValue.build());
          onChanged();
        } else {
          postItsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPostIts(
          int index, nl.hu.blackboard.data.PostItProtos.PostIt.Builder builderForValue) {
        if (postItsBuilder_ == null) {
          ensurePostItsIsMutable();
          postIts_.add(index, builderForValue.build());
          onChanged();
        } else {
          postItsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPostIts(
          java.lang.Iterable<? extends nl.hu.blackboard.data.PostItProtos.PostIt> values) {
        if (postItsBuilder_ == null) {
          ensurePostItsIsMutable();
          super.addAll(values, postIts_);
          onChanged();
        } else {
          postItsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPostIts() {
        if (postItsBuilder_ == null) {
          postIts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          postItsBuilder_.clear();
        }
        return this;
      }
      public Builder removePostIts(int index) {
        if (postItsBuilder_ == null) {
          ensurePostItsIsMutable();
          postIts_.remove(index);
          onChanged();
        } else {
          postItsBuilder_.remove(index);
        }
        return this;
      }
      public nl.hu.blackboard.data.PostItProtos.PostIt.Builder getPostItsBuilder(
          int index) {
        return getPostItsFieldBuilder().getBuilder(index);
      }
      public nl.hu.blackboard.data.PostItProtos.PostItOrBuilder getPostItsOrBuilder(
          int index) {
        if (postItsBuilder_ == null) {
          return postIts_.get(index);  } else {
          return postItsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends nl.hu.blackboard.data.PostItProtos.PostItOrBuilder> 
           getPostItsOrBuilderList() {
        if (postItsBuilder_ != null) {
          return postItsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(postIts_);
        }
      }
      public nl.hu.blackboard.data.PostItProtos.PostIt.Builder addPostItsBuilder() {
        return getPostItsFieldBuilder().addBuilder(
            nl.hu.blackboard.data.PostItProtos.PostIt.getDefaultInstance());
      }
      public nl.hu.blackboard.data.PostItProtos.PostIt.Builder addPostItsBuilder(
          int index) {
        return getPostItsFieldBuilder().addBuilder(
            index, nl.hu.blackboard.data.PostItProtos.PostIt.getDefaultInstance());
      }
      public java.util.List<nl.hu.blackboard.data.PostItProtos.PostIt.Builder> 
           getPostItsBuilderList() {
        return getPostItsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          nl.hu.blackboard.data.PostItProtos.PostIt, nl.hu.blackboard.data.PostItProtos.PostIt.Builder, nl.hu.blackboard.data.PostItProtos.PostItOrBuilder> 
          getPostItsFieldBuilder() {
        if (postItsBuilder_ == null) {
          postItsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              nl.hu.blackboard.data.PostItProtos.PostIt, nl.hu.blackboard.data.PostItProtos.PostIt.Builder, nl.hu.blackboard.data.PostItProtos.PostItOrBuilder>(
                  postIts_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          postIts_ = null;
        }
        return postItsBuilder_;
      }
      
      // optional string readOwner = 4;
      private java.lang.Object readOwner_ = "";
      public boolean hasReadOwner() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getReadOwner() {
        java.lang.Object ref = readOwner_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          readOwner_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReadOwner(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        readOwner_ = value;
        onChanged();
        return this;
      }
      public Builder clearReadOwner() {
        bitField0_ = (bitField0_ & ~0x00000008);
        readOwner_ = getDefaultInstance().getReadOwner();
        onChanged();
        return this;
      }
      void setReadOwner(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        readOwner_ = value;
        onChanged();
      }
      
      // optional int64 currentTimeStep = 5;
      private long currentTimeStep_ ;
      public boolean hasCurrentTimeStep() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getCurrentTimeStep() {
        return currentTimeStep_;
      }
      public Builder setCurrentTimeStep(long value) {
        bitField0_ |= 0x00000010;
        currentTimeStep_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentTimeStep() {
        bitField0_ = (bitField0_ & ~0x00000010);
        currentTimeStep_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .nl.hu.blackboard.data.PostItBox.Filter filter = 6;
      private nl.hu.blackboard.data.PostItProtos.PostItBox.Filter filter_ = nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          nl.hu.blackboard.data.PostItProtos.PostItBox.Filter, nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.Builder, nl.hu.blackboard.data.PostItProtos.PostItBox.FilterOrBuilder> filterBuilder_;
      public boolean hasFilter() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public nl.hu.blackboard.data.PostItProtos.PostItBox.Filter getFilter() {
        if (filterBuilder_ == null) {
          return filter_;
        } else {
          return filterBuilder_.getMessage();
        }
      }
      public Builder setFilter(nl.hu.blackboard.data.PostItProtos.PostItBox.Filter value) {
        if (filterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          filter_ = value;
          onChanged();
        } else {
          filterBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setFilter(
          nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.Builder builderForValue) {
        if (filterBuilder_ == null) {
          filter_ = builderForValue.build();
          onChanged();
        } else {
          filterBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeFilter(nl.hu.blackboard.data.PostItProtos.PostItBox.Filter value) {
        if (filterBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              filter_ != nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDefaultInstance()) {
            filter_ =
              nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.newBuilder(filter_).mergeFrom(value).buildPartial();
          } else {
            filter_ = value;
          }
          onChanged();
        } else {
          filterBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearFilter() {
        if (filterBuilder_ == null) {
          filter_ = nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.getDefaultInstance();
          onChanged();
        } else {
          filterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      public nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.Builder getFilterBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getFilterFieldBuilder().getBuilder();
      }
      public nl.hu.blackboard.data.PostItProtos.PostItBox.FilterOrBuilder getFilterOrBuilder() {
        if (filterBuilder_ != null) {
          return filterBuilder_.getMessageOrBuilder();
        } else {
          return filter_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          nl.hu.blackboard.data.PostItProtos.PostItBox.Filter, nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.Builder, nl.hu.blackboard.data.PostItProtos.PostItBox.FilterOrBuilder> 
          getFilterFieldBuilder() {
        if (filterBuilder_ == null) {
          filterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              nl.hu.blackboard.data.PostItProtos.PostItBox.Filter, nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.Builder, nl.hu.blackboard.data.PostItProtos.PostItBox.FilterOrBuilder>(
                  filter_,
                  getParentForChildren(),
                  isClean());
          filter_ = null;
        }
        return filterBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:nl.hu.blackboard.data.PostItBox)
    }
    
    static {
      defaultInstance = new PostItBox(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nl.hu.blackboard.data.PostItBox)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nl_hu_lcv_blackboard_data_PostIt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nl_hu_lcv_blackboard_data_PostIt_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nl_hu_lcv_blackboard_data_PostItBox_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nl_hu_lcv_blackboard_data_PostItBox_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014PostIt.proto\022\031nl.hu.blackboard.dat" +
      "a\"t\n\006PostIt\022\020\n\010timestep\030\001 \001(\003\022\017\n\007payload" +
      "\030\002 \002(\t\022\r\n\005owner\030\003 \001(\t\022\023\n\013isProcessed\030\004 \001" +
      "(\010\022\017\n\007ordinal\030\005 \001(\005\022\022\n\nproductRef\030\006 \001(\t\"" +
      "\212\002\n\tPostItBox\022\017\n\007isWrite\030\001 \002(\010\022\014\n\004zone\030\002" +
      " \002(\t\0222\n\007postIts\030\003 \003(\0132!.nl.hu.blackb" +
      "oard.data.PostIt\022\021\n\treadOwner\030\004 \001(\t\022\027\n\017c" +
      "urrentTimeStep\030\005 \001(\003\022;\n\006filter\030\006 \001(\0132+.n" +
      "l.hu.blackboard.data.PostItBox.Filte" +
      "r\032A\n\006Filter\022\022\n\nfiltername\030\001 \002(\t\022\021\n\tagent",
      "name\030\002 \003(\t\022\020\n\010deadline\030\003 \001(\003B)\n\031nl.hu.lc" +
      "v.blackboard.dataB\014PostItProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nl_hu_lcv_blackboard_data_PostIt_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nl_hu_lcv_blackboard_data_PostIt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nl_hu_lcv_blackboard_data_PostIt_descriptor,
              new java.lang.String[] { "Timestep", "Payload", "Owner", "IsProcessed", "Ordinal", "ProductRef", },
              nl.hu.blackboard.data.PostItProtos.PostIt.class,
              nl.hu.blackboard.data.PostItProtos.PostIt.Builder.class);
          internal_static_nl_hu_lcv_blackboard_data_PostItBox_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_nl_hu_lcv_blackboard_data_PostItBox_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nl_hu_lcv_blackboard_data_PostItBox_descriptor,
              new java.lang.String[] { "IsWrite", "Zone", "PostIts", "ReadOwner", "CurrentTimeStep", "Filter", },
              nl.hu.blackboard.data.PostItProtos.PostItBox.class,
              nl.hu.blackboard.data.PostItProtos.PostItBox.Builder.class);
          internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_descriptor =
            internal_static_nl_hu_lcv_blackboard_data_PostItBox_descriptor.getNestedTypes().get(0);
          internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nl_hu_lcv_blackboard_data_PostItBox_Filter_descriptor,
              new java.lang.String[] { "Filtername", "Agentname", "Deadline", },
              nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.class,
              nl.hu.blackboard.data.PostItProtos.PostItBox.Filter.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
