#include "ros/console.h"
#include <sstream>

//DEBUG
#define REXOS_DEBUG(...) 													ROS_DEBUG(__VA_ARGS__)
#define REXOS_DEBUG_STREAM(args)											ROS_DEBUG_STREAM(args)
#define REXOS_DEBUG_NAMED(name, ...)										ROS_DEBUG_NAMED(name, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_NAMED(name, args)								ROS_DEBUG_STREAM_NAMED(name, args)
#define REXOS_DEBUG_COND(cond, ...)											ROS_DEBUG_COND(cond, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_COND(cond, args)									ROS_DEBUG_STREAM_COND(cond, args)
#define REXOS_DEBUG_COND_NAMED(cond, name, ...)								ROS_DEBUG_COND_NAMED(cond, name, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_COND_NAMED(cond, name, args)						ROS_DEBUG_STREAM_COND_NAMED(cond, name, args)
#define REXOS_DEBUG_ONCE(...)												ROS_DEBUG_ONCE(__VA_ARGS__)
#define REXOS_DEBUG_STREAM_ONCE(args)										ROS_DEBUG_STREAM_ONCE(args)
#define REXOS_DEBUG_ONCE_NAMED(name, ...)									ROS_DEBUG_ONCE_NAMED(name, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_ONCE_NAMED(name, args)							ROS_DEBUG_STREAM_ONCE_NAMED(name, args)
#define REXOS_DEBUG_THROTTLE(rate, ...)										ROS_DEBUG_THROTTLE(rate, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_THROTTLE(rate, args)								ROS_DEBUG_STREAM_THROTTLE(rate, args)
#define REXOS_DEBUG_THROTTLE_NAMED(rate, name, ...)							ROS_DEBUG_THROTTLE_NAMED(rate, name, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_THROTTLE_NAMED(rate, name, args)					ROS_DEBUG_STREAM_THROTTLE_NAMED(rate, name, args)
#define REXOS_DEBUG_FILTER(filter, ...)										ROS_DEBUG_FILTER(filter, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_FILTER(filter, args)								ROS_DEBUG_STREAM_FILTER(filter, args)
#define REXOS_DEBUG_FILTER_NAMED(filter, name, ...)							ROS_DEBUG_FILTER_NAMED(filter, name, __VA_ARGS__)
#define REXOS_DEBUG_STREAM_FILTER_NAMED(filter, name, args)					ROS_DEBUG_STREAM_FILTER_NAMED(filter, name, args)

//INFO
#define REXOS_INFO(...) 													ROS_INFO(__VA_ARGS__)
#define REXOS_INFO_STREAM(args) 											ROS_INFO_STREAM(args)
#define REXOS_INFO_NAMED(name, ...) 										ROS_INFO_NAMED(name, __VA_ARGS__)
#define REXOS_INFO_STREAM_NAMED(name, args) 								ROS_INFO_STREAM_NAMED(name, args)
#define REXOS_INFO_COND(cond, ...) 											ROS_INFO_COND(cond, __VA_ARGS__)
#define REXOS_INFO_STREAM_COND(cond, args) 									ROS_INFO_STREAM_COND(cond, args) 
#define REXOS_INFO_COND_NAMED(cond, name, ...) 								ROS_INFO_COND_NAMED(cond, name, __VA_ARGS__)
#define REXOS_INFO_STREAM_COND_NAMED(cond, name, args) 						ROS_INFO_STREAM_COND_NAMED(cond, name, args)
#define REXOS_INFO_ONCE(...) 												ROS_INFO_ONCE(__VA_ARGS__)
#define REXOS_INFO_STREAM_ONCE(args) 										ROS_INFO_STREAM_ONCE(args)
#define REXOS_INFO_ONCE_NAMED(name, ...) 									ROS_INFO_ONCE_NAMED(name, __VA_ARGS__)
#define REXOS_INFO_STREAM_ONCE_NAMED(name, args) 							ROS_INFO_STREAM_ONCE_NAMED(name, args)
#define REXOS_INFO_THROTTLE(rate, ...) 										ROS_INFO_THROTTLE(rate, __VA_ARGS__)
#define REXOS_INFO_STREAM_THROTTLE(rate, args) 								ROS_INFO_STREAM_THROTTLE(rate, args)
#define REXOS_INFO_THROTTLE_NAMED(rate, name, ...) 							ROS_INFO_THROTTLE_NAMED(rate, name, __VA_ARGS__)
#define REXOS_INFO_STREAM_THROTTLE_NAMED(rate, name, args) 					ROS_INFO_STREAM_THROTTLE_NAMED(rate, name, args)
#define REXOS_INFO_FILTER(filter, ...) 										ROS_INFO_FILTER(filter, __VA_ARGS__)
#define REXOS_INFO_STREAM_FILTER(filter, args) 								ROS_INFO_STREAM_FILTER(filter, args)
#define REXOS_INFO_FILTER_NAMED(filter, name, ...) 							ROS_INFO_FILTER_NAMED(filter, name, __VA_ARGS__)
#define REXOS_INFO_STREAM_FILTER_NAMED(filter, name, args) 					ROS_INFO_STREAM_FILTER_NAMED(filter, name, args)

//WARN
#define REXOS_WARN(...)														ROS_WARN(__VA_ARGS__)	
#define REXOS_WARN_STREAM(args)												ROS_WARN_STREAM(args)
#define REXOS_WARN_NAMED(name, ...)											ROS_WARN_NAMED(name, __VA_ARGS__)
#define REXOS_WARN_STREAM_NAMED(name, args)									ROS_WARN_STREAM_NAMED(name, args)
#define REXOS_WARN_COND(cond, ...)											ROS_WARN_COND(cond, __VA_ARGS__)
#define REXOS_WARN_STREAM_COND(cond, args)									ROS_WARN_STREAM_COND(cond, args)
#define REXOS_WARN_COND_NAMED(cond, name, ...)								ROS_WARN_COND_NAMED(cond, name, __VA_ARGS__)
#define REXOS_WARN_STREAM_COND_NAMED(cond, name, args)						ROS_WARN_STREAM_COND_NAMED(cond, name, args)
#define REXOS_WARN_ONCE(...)												ROS_WARN_ONCE(__VA_ARGS__)
#define REXOS_WARN_STREAM_ONCE(args)										ROS_WARN_STREAM_ONCE(args)
#define REXOS_WARN_ONCE_NAMED(name, ...)									ROS_WARN_ONCE_NAMED(name, __VA_ARGS__)
#define REXOS_WARN_STREAM_ONCE_NAMED(name, args)							ROS_WARN_STREAM_ONCE_NAMED(name, args)
#define REXOS_WARN_THROTTLE(rate, ...)										ROS_WARN_THROTTLE(rate, __VA_ARGS__)
#define REXOS_WARN_STREAM_THROTTLE(rate, args)								ROS_WARN_STREAM_THROTTLE(rate, args)
#define REXOS_WARN_THROTTLE_NAMED(rate, name, ...)							ROS_WARN_THROTTLE_NAMED(rate, name, __VA_ARGS__)
#define REXOS_WARN_STREAM_THROTTLE_NAMED(rate, name, args)					ROS_WARN_STREAM_THROTTLE_NAMED(rate, name, args)
#define REXOS_WARN_FILTER(filter, ...)										ROS_WARN_FILTER(filter, __VA_ARGS__)
#define REXOS_WARN_STREAM_FILTER(filter, args)								ROS_WARN_STREAM_FILTER(filter, args)
#define REXOS_WARN_FILTER_NAMED(filter, name, ...)							ROS_WARN_FILTER_NAMED(filter, name, __VA_ARGS__)
#define REXOS_WARN_STREAM_FILTER_NAMED(filter, name, args)					ROS_WARN_STREAM_FILTER_NAMED(filter, name, args)

//ERROR
#define REXOS_ERROR(...)													ROS_ERROR(__VA_ARGS__)	
#define REXOS_ERROR_STREAM(args)											ROS_ERROR_STREAM(args)
#define REXOS_ERROR_NAMED(name, ...)										ROS_ERROR_NAMED(name, __VA_ARGS__)
#define REXOS_ERROR_STREAM_NAMED(name, args)								ROS_ERROR_STREAM_NAMED(name, args)
#define REXOS_ERROR_COND(cond, ...)											ROS_ERROR_COND(cond, __VA_ARGS__)
#define REXOS_ERROR_STREAM_COND(cond, args)									ROS_ERROR_STREAM_COND(cond, args)
#define REXOS_ERROR_COND_NAMED(cond, name, ...)								ROS_ERROR_COND_NAMED(cond, name, __VA_ARGS__)
#define REXOS_ERROR_STREAM_COND_NAMED(cond, name, args)						ROS_ERROR_STREAM_COND_NAMED(cond, name, args)
#define REXOS_ERROR_ONCE(...)												ROS_ERROR_ONCE(__VA_ARGS__)
#define REXOS_ERROR_STREAM_ONCE(args)										ROS_ERROR_STREAM_ONCE(args)
#define REXOS_ERROR_ONCE_NAMED(name, ...)									ROS_ERROR_ONCE_NAMED(name, __VA_ARGS__)
#define REXOS_ERROR_STREAM_ONCE_NAMED(name, args)							ROS_ERROR_STREAM_ONCE_NAMED(name, args)
#define REXOS_ERROR_THROTTLE(rate, ...)										ROS_ERROR_THROTTLE(rate, __VA_ARGS__)
#define REXOS_ERROR_STREAM_THROTTLE(rate, args)								ROS_ERROR_STREAM_THROTTLE(rate, args)
#define REXOS_ERROR_THROTTLE_NAMED(rate, name, ...)							ROS_ERROR_THROTTLE_NAMED(rate, name, __VA_ARGS__)
#define REXOS_ERROR_STREAM_THROTTLE_NAMED(rate, name, args)					ROS_ERROR_STREAM_THROTTLE_NAMED(rate, name, args)
#define REXOS_ERROR_FILTER(filter, ...)										ROS_ERROR_FILTER(filter, __VA_ARGS__)
#define REXOS_ERROR_STREAM_FILTER(filter, args)								ROS_ERROR_STREAM_FILTER(filter, args)
#define REXOS_ERROR_FILTER_NAMED(filter, name, ...)							ROS_ERROR_FILTER_NAMED(filter, name, __VA_ARGS__)
#define REXOS_ERROR_STREAM_FILTER_NAMED(filter, name, args)					ROS_ERROR_STREAM_FILTER_NAMED(filter, name, args)

//FATAL
#define REXOS_FATAL(...)													ROS_FATAL(__VA_ARGS__)	
#define REXOS_FATAL_STREAM(args)											ROS_FATAL_STREAM(args)
#define REXOS_FATAL_NAMED(name, ...)										ROS_FATAL_NAMED(name, __VA_ARGS__)
#define REXOS_FATAL_STREAM_NAMED(name, args)								ROS_FATAL_STREAM_NAMED(name, args)
#define REXOS_FATAL_COND(cond, ...)											ROS_FATAL_COND(cond, __VA_ARGS__)
#define REXOS_FATAL_STREAM_COND(cond, args)									ROS_FATAL_STREAM_COND(cond, args)
#define REXOS_FATAL_COND_NAMED(cond, name, ...)								ROS_FATAL_COND_NAMED(cond, name, __VA_ARGS__)
#define REXOS_FATAL_STREAM_COND_NAMED(cond, name, args)						ROS_FATAL_STREAM_COND_NAMED(cond, name, args)
#define REXOS_FATAL_ONCE(...)												ROS_FATAL_ONCE(__VA_ARGS__)
#define REXOS_FATAL_STREAM_ONCE(args)										ROS_FATAL_STREAM_ONCE(args)
#define REXOS_FATAL_ONCE_NAMED(name, ...)									ROS_FATAL_ONCE_NAMED(name, __VA_ARGS__)
#define REXOS_FATAL_STREAM_ONCE_NAMED(name, args)							ROS_FATAL_STREAM_ONCE_NAMED(name, args)
#define REXOS_FATAL_THROTTLE(rate, ...)										ROS_FATAL_THROTTLE(rate, __VA_ARGS__)
#define REXOS_FATAL_STREAM_THROTTLE(rate, args)								ROS_FATAL_STREAM_THROTTLE(rate, args)
#define REXOS_FATAL_THROTTLE_NAMED(rate, name, ...)							ROS_FATAL_THROTTLE_NAMED(rate, name, __VA_ARGS__)
#define REXOS_FATAL_STREAM_THROTTLE_NAMED(rate, name, args)					ROS_FATAL_STREAM_THROTTLE_NAMED(rate, name, args)
#define REXOS_FATAL_FILTER(filter, ...)										ROS_FATAL_FILTER(filter, __VA_ARGS__)
#define REXOS_FATAL_STREAM_FILTER(filter, args)								ROS_FATAL_STREAM_FILTER(filter, args)
#define REXOS_FATAL_FILTER_NAMED(filter, name, ...)							ROS_FATAL_FILTER_NAMED(filter, name, __VA_ARGS__)
#define REXOS_FATAL_STREAM_FILTER_NAMED(filter, name, args)					ROS_FATAL_STREAM_FILTER_NAMED(filter, name, args)
