package HAL.listeners;

/**
 * A BlackBoardListener listens to changes on the blackboard which are usually generated by ROS.
 * @author Bas Voskuijlen
 *
 */
public interface BlackboardEquipletListener {
	/**
	 * This method is called when the MAST state of the equiplet changes
	 * @param equipletName
	 * @param state
	 */
	public void OnEquipletStateChanged(String state);
	/**
	 * This method is called when the MAST mode of the equiplet changes
	 * @param equipletName
	 * @param state
	 */
	public void OnEquipletModeChanged(String mode);
}
