package HAL.tasks;

import java.util.ArrayList;

import libraries.utillities.log.LogLevel;
import libraries.utillities.log.LogSection;
import libraries.utillities.log.Logger;
import HAL.Module;
import HAL.exceptions.HardwareAbstractionLayerProcessException;
import HAL.factories.ModuleFactory;
import HAL.listeners.HardwareAbstractionLayerListener;
import HAL.listeners.ProcessListener;
import HAL.steps.HardwareStep;
/**
 * The thread that manages the execution of hardware steps
 * @author Bas Voskuijlen
 *
 */
public class ExecutionProcess implements Runnable, ProcessListener{
	private HardwareAbstractionLayerListener hardwareAbstractionLayerListener;
	private ArrayList<HardwareStep> hardwareSteps;
	private ModuleFactory moduleFactory;
	/**
	 * Constructs the ExecutionProcess but does NOT start it.
	 * @param hardwareAbstractionLayerListener
	 * @param hardwareSteps
	 * @param moduleFactory
	 */
	public ExecutionProcess(HardwareAbstractionLayerListener hardwareAbstractionLayerListener, ArrayList<HardwareStep> hardwareSteps, ModuleFactory moduleFactory){
		this.hardwareAbstractionLayerListener = hardwareAbstractionLayerListener;
		this.hardwareSteps = new ArrayList<HardwareStep>();
		this.hardwareSteps.addAll(hardwareSteps);
		this.moduleFactory = moduleFactory;
	}

	/**
	 * This method will execute the HardwareSteps in chronological order.
	 * This method returns after all HardwareSteps for this ExecutionProcess have been executed and therefore should be called asynchronous. This should be done with the start method.
	 */
	@Override
	public synchronized void run() {
		Logger.log(LogSection.HAL_EXECUTION, LogLevel.INFORMATION, "Execution started with the following hardware steps:", hardwareSteps);
		try {
			while (hardwareSteps.size() > 0){
				moduleFactory.executeHardwareStep(this, hardwareSteps.get(0));
				this.wait();
			}
			hardwareAbstractionLayerListener.onExecutionFinished();
		} catch (Exception ex) {
			// TODO Auto-generated catch block
			ex.printStackTrace();
		}
	}
	
	/**
	 * This method handles the onProcessStateChanged events generated by the modules. It will notify the run method when necessary.
	 * Do not call this method! 
	 */
	@Override
	public synchronized void onProcessStateChanged(String status, long hardwareStepSerialId, Module module) throws HardwareAbstractionLayerProcessException{
		Logger.log(LogSection.HAL_EXECUTION, LogLevel.DEBUG, "The status of hardwareStep identified by " + 
				hardwareStepSerialId + " (being processed by module " + module + ") has changed to " + status);
		if(status.equals("DONE")){
			if (hardwareSteps.size() > 0){
				HardwareStep hardwareStep = hardwareSteps.get(0);
				hardwareAbstractionLayerListener.onProcessStatusChanged(status, module, hardwareStep);
				hardwareSteps.remove(0);
				try {
					Thread.sleep(500);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				this.notify();
			}
			else {
				throw new HardwareAbstractionLayerProcessException("No more hardwareSteps while there should be at least one more");
			}
		}
		else {
			if (hardwareSteps.size() > 0){
				HardwareStep hardwareStep = hardwareSteps.get(0);
				hardwareAbstractionLayerListener.onProcessStatusChanged(status, module, hardwareStep);	
			}
			//hardwareSteps.clear();
			
		}
	}
	
	/**
	 * This method starts the ExecutionProcess asynchronously.
	 */
	public void start() {
		Thread t = new Thread(this);
		t.start();
	}
}
