package HAL.listeners;

import org.json.JSONException;

import HAL.libraries.blackboard_client.data_classes.GeneralMongoException;
import HAL.libraries.blackboard_client.data_classes.InvalidDBNamespaceException;
import HAL.libraries.blackboard_client.data_classes.InvalidJSONException;

/**
 * A BlackBoardListener listens to changes on the blackboard which are usually generated by ROS.
 * 
 * @author Bas Voskuijlen
 * @author Lars Veenendaal
 */
public interface BlackboardEquipletListener {
	/**
	 * This method is called when the MAST state of the equiplet changes
	 * @param state
	 */
	public void onEquipletStateChanged(String state);
	/**
	 * This method is called when the MAST mode of the equiplet changes
	 * @param mode
	 */
	public void onEquipletModeChanged(String mode);
	/**
	 * This method is called when the MAST mode of the equiplet is supposed to Reload
	 * @param state
	 */
	public void onReloadEquiplet(String state);
	/**
	 * 
	 * [sendReloadEquiplet - This method is called when the MAST mode of the equiplet is supposed to Reload - UNTESTED W.I.P (Lars Veenendaal)]
	 * @throws GeneralMongoException 
	 * @throws InvalidDBNamespaceException 
	 * @throws InvalidJSONException 
	 * @throws JSONException 
	 */
	public void sendReloadEquiplet() throws JSONException, InvalidJSONException, InvalidDBNamespaceException, GeneralMongoException;
}
