package HAL.listeners;

import HAL.steps.HardwareStep;
import HAL.steps.HardwareStep.HardwareStepStatus;

/**
 * A BlackBoardListener listens to changes on the blackboard which are usually generated by ROS.
 * @author Bas Voskuijlen
 *
 */
public interface BlackboardModuleListener {
	/**
	 * This method is called when the status of a {@link HardwareStep} changes
	 * @param equipletName
	 * @param state
	 */
	public void onProcessStatusChanged(HardwareStepStatus status, String serialId);
	/**
	 * This method is called when the MAST state of the module changes
	 * @param equipletName
	 * @param state
	 */
	public void onModuleStateChanged(String state);
	/**
	 * This method is called when the MAST mode of the module changes
	 * @param equipletName
	 * @param state
	 */
	public void onModuleModeChanged(String mode);
}
