package HAL.listeners;

import HAL.steps.HardwareStep;
import HAL.steps.HardwareStep.HardwareStepStatus;

/**
 * A BlackBoardListener listens to changes on the blackboard which are usually generated by ROS.
 * @author Bas Voskuijlen
 *
 */
public interface BlackboardProcessListener {
	/**
	 * This method is called when the status of a {@link HardwareStep} changes
	 * @param equipletName
	 * @param state
	 */
	public void onProcessStatusChanged(HardwareStepStatus status, String serialId);
}
