package HAL.listeners;

import org.json.JSONObject;

/**
 * A BlackBoardListener listens to changes on the blackboard which are usually generated by ROS.
 * 
 * @author Bas Voskuijlen
 * @author Lars Veenendaal
 */
public interface EquipletCommandListener {
	public enum EquipletCommandStatus {
		WAITING, IN_PROGRESS, DONE, FAILED
	}
	public void onEquipletCommandReply(JSONObject reply);

	public void onEquipletCommandStatusChanged(EquipletCommandStatus status);
}
