package HAL.listeners;

import generic.Mast;

/**
 * A BlackBoardListener listens to changes on the blackboard which are usually generated by ROS.
 * 
 * @author Bas Voskuijlen
 * @author Lars Veenendaal
 */
public interface EquipletListener extends EquipletCommandListener {
	/**
	 * This method is called when the MAST state of the equiplet changes
	 * @param state
	 */
	public void onEquipletStateChanged(Mast.State state);
	/**
	 * This method is called when the MAST mode of the equiplet changes
	 * @param mode
	 */
	public void onEquipletModeChanged(Mast.Mode mode);
}
