package HAL.steps;

import generic.ProductStep;


import HAL.Capability;
import HAL.Module;

import com.google.gson.JsonObject;

/**
 * A CompositeStep is a step composed of multiple abstract {@link HardwareStep}s.
 * CompositeSteps are generated by {@link Capability} and interpeted by {@link Module}s.
 * @author Tommas Bakker
 *
 */
public class CompositeStep{
	private ProductStep productStep;
	private JsonObject command;
	
	public CompositeStep(ProductStep productStep, JsonObject command){
		this.command = command;
		this.productStep = productStep;
	}
	
	public ProductStep getProductStep(){
		return this.productStep;
	}
	public JsonObject getCommand(){
		return this.command;
	}
}
