package HAL.steps;

import java.io.Serializable;

import HAL.Module;
import HAL.ModuleIdentifier;

import com.google.gson.JsonObject;

/**
 * A HardwareStep is a step that is completely translated and can be processed by the ROS node corresponding to this HardwareStep.
 * HardwareSteps are generated by {@link Module}s and interpeted by ROS.
 * @author Tommas Bakker
 *
 */
public class HardwareStep implements Serializable {
	private static final long serialVersionUID = 3031019032556167945L;
	private CompositeStep compositeStep;
	private JsonObject rosCommand;
	private ModuleIdentifier moduleIdentifier;
	
	public HardwareStep(CompositeStep compositeStep, JsonObject rosCommand, ModuleIdentifier moduleIdentifier){
		this.moduleIdentifier = moduleIdentifier;
		this.rosCommand = rosCommand;
		this.compositeStep = compositeStep;
	}
	
	public CompositeStep getCompositeStep(){
		return this.compositeStep;
	}
	public JsonObject getRosCommand(){
		return this.rosCommand;
	}
	public ModuleIdentifier getModuleIdentifier(){
		return this.moduleIdentifier;
	}
}
