/**
 * @file CameraNode.cpp
 * @brief Camera node
 * @date Created: 2013-10-23
 * 
 * @author Tommas Bakker
 * 
 * @section LICENSE 
 * Copyright © 2012, HU University of Applied Sciences Utrecht. 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * - Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * - Neither the name of the HU University of Applied Sciences Utrecht nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE HU UNIVERSITY OF APPLIED SCIENCES UTRECHT
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **/

#include "vision_node/VisionNode.h"
#include "rexos_utilities/Utilities.h"

#include <camera/unicap_cv_bridge.h>

#include <stdexcept>

int main(int argc, char* argv[]) {
	ros::init(argc, argv, "vision_node");
	ROS_INFO("This node must be run with ROOT priveleges when using the DFK 22AUC03");
	
	// Check arguments
	if(argc < 3) {
		ROS_ERROR(
			"Not enough arguments, please specify the following arguments \"device number\", \"format number\", [\"correction xml generated by the camera correction tool\"]"
		);
		exit(-1);
	}
	std::vector<std::string> devices;
	devices = unicap_cv_bridge::listDevices();
	std::cout << "Devices:" << std::endl;
	for(int i = 0; i < devices.size(); i++){
		std::cout << "\t" << devices[i] << std::endl;
	}
	
	int deviceNumber;
	try{
		deviceNumber = rexos_utilities::stringToInt(argv[1]);
	} catch(std::runtime_error ex){
		ROS_ERROR("Device number is not a valid number.");
		exit(-2);
	}
	
	std::vector<std::string> formats;
	formats = unicap_cv_bridge::listFormats(deviceNumber);
	std::cout << "Formats:" << std::endl;
	for(int i = 0; i < formats.size(); i++){
		std::cout << "\t" << formats[i] << std::endl;
	}

	int formatNumber;
	try{
		formatNumber = rexos_utilities::stringToInt(argv[2]);
	} catch(std::runtime_error ex){
		ROS_ERROR("Format number is not a valid number.");
		exit(-3);
	}
	
	VisionNode visionNode(deviceNumber, formatNumber, std::string());
	visionNode.run();

	return 0;
}